# Generated by Django 6.0.6 on 2026-06-13 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=512, verbose_name='头像链接')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='当前城市')),
                ('occupation', models.CharField(blank=True, max_length=128, verbose_name='职业或行业')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('birthday_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='生日月份')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('phone_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('selected', '指定同学可见'), ('only_me', '仅自己可见')], default='only_me', max_length=16, verbose_name='手机号可见范围')),
                ('wechat', models.CharField(blank=True, max_length=64, verbose_name='微信号')),
                ('wechat_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('selected', '指定同学可见'), ('only_me', '仅自己可见')], default='only_me', max_length=16, verbose_name='微信号可见范围')),
                ('email_visibility', models.CharField(choices=[('everyone', '所有人可见'), ('selected', '指定同学可见'), ('only_me', '仅自己可见')], default='only_me', max_length=16, verbose_name='邮箱可见范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact_visible_to', models.ManyToManyField(blank=True, related_name='visible_to_profiles', to=settings.AUTH_USER_MODEL, verbose_name='指定可见的同学')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
                'ordering': ['user__real_name'],
            },
        ),
    ]
