# Generated by Django 6.0.6 on 2026-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_birthday',
            field=models.BooleanField(default=False, verbose_name='在生日板块展示生日月份'),
        ),
    ]
