# Generated by Django 6.0.6 on 2026-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_show_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_visible',
            field=models.BooleanField(default=True, verbose_name='头像公开展示'),
        ),
    ]
