# Generated by Django 6.0.6 on 2026-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_avatar_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_name_visible',
            field=models.BooleanField(default=False, verbose_name='真实姓名公开展示'),
        ),
    ]
