# Generated by Django 6.0.6 on 2026-06-13 06:33

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='账号唯一标识')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('real_name', models.CharField(max_length=64, verbose_name='真实姓名')),
                ('high_school', models.CharField(max_length=128, verbose_name='高三所在学校')),
                ('high_school_class', models.CharField(max_length=128, verbose_name='高三所在班级')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='外号')),
                ('extra_info', models.TextField(blank=True, verbose_name='其它信息')),
                ('role', models.CharField(choices=[('classmate', '普通同学'), ('moderator', '管理会员'), ('super_admin', '超级管理员')], default='classmate', max_length=32, verbose_name='角色')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('need_more_info', '需补充资料')], db_index=True, default='pending', max_length=32, verbose_name='审核状态')),
                ('account_status', models.CharField(choices=[('normal', '正常'), ('restricted', '已限制'), ('banned', '已封禁')], db_index=True, default='normal', max_length=32, verbose_name='账号状态')),
                ('review_note', models.TextField(blank=True, verbose_name='内部审核备注')),
                ('review_message', models.TextField(blank=True, verbose_name='给用户的审核说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('is_staff', models.BooleanField(default=False, verbose_name='员工状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='可登录')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_users', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
