# Generated by Django 6.0.6 on 2026-06-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('delete_reason', models.CharField(blank=True, max_length=256, verbose_name='删除原因')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('category', models.CharField(choices=[('campus', '高中校园'), ('graduation', '毕业照'), ('teacher', '老师合影'), ('gathering', '聚会照片'), ('classmate_life', '同学近况'), ('memory', '班级纪念')], default='memory', max_length=32, verbose_name='分类')),
                ('creator_name_snapshot', models.CharField(max_length=64, verbose_name='创建人姓名快照')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除'), ('pending_review', '待审核')], db_index=True, default='published', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='activities.activity', verbose_name='关联活动')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_albums', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('delete_reason', models.CharField(blank=True, max_length=256, verbose_name='删除原因')),
                ('uploader_name_snapshot', models.CharField(max_length=64, verbose_name='上传人姓名快照')),
                ('caption', models.TextField(blank=True, verbose_name='图片说明')),
                ('display_mode', models.CharField(choices=[('real_name', '真实姓名'), ('nickname', '昵称')], default='real_name', max_length=16, verbose_name='展示身份')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除'), ('pending_review', '待审核')], db_index=True, default='published', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album', verbose_name='相册')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='common.media', verbose_name='媒体文件')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='albums.photo', verbose_name='封面照片'),
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('delete_reason', models.CharField(blank=True, max_length=256, verbose_name='删除原因')),
                ('content', models.TextField(verbose_name='内容')),
                ('display_mode', models.CharField(choices=[('real_name', '真实姓名'), ('nickname', '昵称')], default='real_name', max_length=16, verbose_name='展示身份')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除'), ('pending_review', '待审核')], db_index=True, default='published', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='albums.photo', verbose_name='照片')),
            ],
            options={
                'verbose_name': '照片评论',
                'verbose_name_plural': '照片评论',
                'ordering': ['created_at'],
            },
        ),
    ]
