# Generated by Django 6.0.6 on 2026-06-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='albums.photocomment', verbose_name='所属一级评论'),
        ),
        migrations.AddField(
            model_name='photocomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_replies', to='albums.photocomment', verbose_name='回复对象'),
        ),
    ]
