# Generated by Django 6.0.6 on 2026-06-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ignore', '忽略举报'), ('hide_content', '隐藏内容'), ('delete_content', '删除内容'), ('request_revision', '要求修改'), ('warn_user', '警告用户'), ('restrict_user', '限制用户'), ('ban_user', '封禁用户')], db_index=True, max_length=32, verbose_name='处理动作')),
                ('reason', models.TextField(blank=True, verbose_name='处理原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '治理动作',
                'verbose_name_plural': '治理动作',
                'ordering': ['-created_at'],
            },
        ),
    ]
