# Generated by Django 6.0.6 on 2026-06-13 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=256, verbose_name='原始文件名')),
                ('content_type', models.CharField(max_length=128, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(verbose_name='文件大小（字节）')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('content_type_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='关联对象类型')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
