# Generated by Django 6.0.6 on 2026-06-13 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('delete_reason', models.CharField(blank=True, max_length=256, verbose_name='删除原因')),
                ('content', models.TextField(verbose_name='祝福内容')),
                ('display_mode', models.CharField(choices=[('real_name', '真实姓名'), ('nickname', '昵称')], default='real_name', max_length=16, verbose_name='展示身份')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除'), ('pending_review', '待审核')], db_index=True, default='published', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_birthday_wishes', to=settings.AUTH_USER_MODEL, verbose_name='祝福发布者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_birthday_wishes', to=settings.AUTH_USER_MODEL, verbose_name='被祝福人')),
            ],
            options={
                'verbose_name': '生日祝福',
                'verbose_name_plural': '生日祝福',
                'ordering': ['-created_at'],
            },
        ),
    ]
