# Generated by Django 6.0.6 on 2026-06-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象 ID')),
                ('reason', models.CharField(choices=[('privacy', '涉及隐私'), ('false_info', '内容不实'), ('abuse', '攻击辱骂'), ('ad', '广告推广'), ('fraud', '诈骗或诱导转账'), ('illegal', '违法违规'), ('copyright', '侵犯肖像权或著作权'), ('other', '其他原因')], max_length=32, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理'), ('ignored', '已忽略')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='举报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='对象类型')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'ordering': ['-created_at'],
            },
        ),
    ]
