# Generated by Django 6.0.6 on 2026-06-13 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('activity_type', models.CharField(choices=[('gathering', '聚会报名'), ('voting', '投票'), ('chain', '接龙')], max_length=16, verbose_name='活动类型')),
                ('initiator_name_snapshot', models.CharField(max_length=64, verbose_name='发起人姓名快照')),
                ('description', models.TextField(verbose_name='活动说明')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='人数上限')),
                ('allow_guests', models.BooleanField(default=False, verbose_name='可带家属')),
                ('contact_info', models.CharField(blank=True, max_length=256, verbose_name='联系人信息')),
                ('status', models.CharField(choices=[('preparing', '筹备中'), ('open', '报名中'), ('closed', '已截止'), ('finished', '已结束'), ('cancelled', '已取消')], db_index=True, default='open', max_length=16, verbose_name='状态')),
                ('is_multi_choice', models.BooleanField(default=False, verbose_name='允许多选')),
                ('show_voter_names', models.BooleanField(default=False, verbose_name='展示投票参与人')),
                ('allow_vote_change', models.BooleanField(default=True, verbose_name='允许修改投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_activities', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='选项')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='activities.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '投票选项',
                'verbose_name_plural': '投票选项',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name_snapshot', models.CharField(max_length=64, verbose_name='姓名快照')),
                ('will_attend', models.BooleanField(default=True, verbose_name='是否参加')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, verbose_name='人数')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填写时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_records', to='activities.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chain_records', to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '接龙记录',
                'verbose_name_plural': '接龙记录',
                'ordering': ['created_at'],
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name_snapshot', models.CharField(max_length=64, verbose_name='姓名快照')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, verbose_name='参加人数')),
                ('bring_guests', models.BooleanField(default=False, verbose_name='带家属')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='activities.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signups', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
            ],
            options={
                'verbose_name': '报名记录',
                'verbose_name_plural': '报名记录',
                'ordering': ['created_at'],
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name_snapshot', models.CharField(max_length=64, verbose_name='姓名快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='activities.voteoption', verbose_name='选项')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_records', to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'ordering': ['created_at'],
                'unique_together': {('option', 'user')},
            },
        ),
    ]
