# Generated by Django 6.0.6 on 2026-06-13 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('category', models.CharField(choices=[('life', '生活近况'), ('old_photos', '老照片'), ('reunion', '同学聚会'), ('teacher', '老师相关'), ('work_city', '工作与城市'), ('family', '家庭与成长'), ('help', '求助与互助'), ('chat', '闲聊')], default='chat', max_length=32, verbose_name='分类')),
                ('display_mode', models.CharField(choices=[('real_name', '真实姓名'), ('nickname', '昵称')], default='real_name', max_length=16, verbose_name='展示身份')),
                ('status', models.CharField(choices=[('published', '已发布'), ('deleted', '已删除')], db_index=True, default='published', max_length=16, verbose_name='状态')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_posts', to=settings.AUTH_USER_MODEL, verbose_name='置顶操作人')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'ordering': ['-is_pinned', '-pinned_at', '-created_at'],
            },
        ),
    ]
