# Generated by Django 6.0.6 on 2026-06-13 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=256, verbose_name='删除原因'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除操作人'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除'), ('pending_review', '待审核')], db_index=True, default='published', max_length=16, verbose_name='状态'),
        ),
    ]
