# Generated by Django 6.0.6 on 2026-06-13 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('review_result', '审核结果'), ('announcement', '公告通知'), ('comment_reply', '评论回复'), ('activity_status', '活动状态'), ('system', '系统通知')], db_index=True, max_length=32, verbose_name='通知类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象 ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_targets', to='contenttypes.contenttype', verbose_name='关联对象类型')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
