# Generated by Django 6.0.6 on 2026-06-14 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('post.created', '动态发布'), ('post.updated', '动态更新'), ('comment.created', '动态评论'), ('album.photo.created', '相册照片上传'), ('photo.comment.created', '照片评论'), ('announcement.created', '公告发布'), ('activity.updated', '活动更新'), ('notification.created', '系统通知创建'), ('notification.read', '系统通知已读')], db_index=True, max_length=64, verbose_name='事件类型')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='目标 ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '实时事件',
                'verbose_name_plural': '实时事件',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['recipient', 'id'], name='notificatio_recipie_c69ffe_idx'), models.Index(fields=['event_type', 'created_at'], name='notificatio_event_t_5280fb_idx')],
            },
        ),
    ]
