# Generated by Django 6.0.6 on 2026-06-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_created', '提交举报'), ('report_handled', '处理举报'), ('content_hidden', '隐藏内容'), ('content_deleted', '删除内容'), ('user_warned', '警告用户'), ('user_restricted', '限制用户'), ('user_banned', '封禁用户')], db_index=True, max_length=64, verbose_name='操作类型')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象 ID')),
                ('reason', models.CharField(blank=True, max_length=512, verbose_name='原因')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_targets', to='contenttypes.contenttype', verbose_name='对象类型')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
