# Generated by Django 6.0.6 on 2026-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('report_created', '提交举报'), ('report_handled', '处理举报'), ('content_hidden', '隐藏内容'), ('content_deleted', '删除内容'), ('user_warned', '警告用户'), ('user_restricted', '限制用户'), ('user_banned', '封禁用户'), ('user_reviewed', '审核用户'), ('role_changed', '角色变更'), ('account_status_changed', '账号状态变更'), ('announcement_created', '发布公告'), ('announcement_updated', '编辑公告'), ('announcement_deleted', '删除公告'), ('activity_status_changed', '活动状态变更'), ('activity_deleted', '删除活动')], db_index=True, max_length=64, verbose_name='操作类型'),
        ),
    ]
